drop table if exists items;
drop table if exists users;
drop table if exists bookings;

CREATE TABLE IF NOT EXISTS users
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
	CONSTRAINT UQ_USER_EMAIL unique (email)
);

CREATE TABLE IF NOT EXISTS items
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR,
    available BOOLEAN,
    owner_id INTEGER REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS bookings (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date timestamp,
    end_date timestamp,
    item_id integer,
    user_id integer,
    status varchar
);